// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqgXrDVhfrLN6szq9wkcUUe4Auz6s9TeQ',
    appId: '1:603060516772:web:067b2f2423dc87777c3331',
    messagingSenderId: '603060516772',
    projectId: 'sign-f17ac',
    authDomain: 'sign-f17ac.firebaseapp.com',
    storageBucket: 'sign-f17ac.appspot.com',
    measurementId: 'G-BTM98EWVER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtUDfKZ2zJucrw3L_BBqVmSZx53W6piXg',
    appId: '1:603060516772:android:ef739276d87633727c3331',
    messagingSenderId: '603060516772',
    projectId: 'sign-f17ac',
    storageBucket: 'sign-f17ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhksttgKnANPpmgwylkqVik97uvYbnev8',
    appId: '1:603060516772:ios:cc0e5c2fc640c7227c3331',
    messagingSenderId: '603060516772',
    projectId: 'sign-f17ac',
    storageBucket: 'sign-f17ac.appspot.com',
    iosClientId: '603060516772-mpbtc17etmdaj0mfjjketd0mt3vh8881.apps.googleusercontent.com',
    iosBundleId: 'com.example.emoradd',
  );
}
